# Generated by Django 4.0.3 on 2022-04-02 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('post_image1', models.ImageField(blank=True, upload_to='post_images')),
                ('post_image2', models.ImageField(blank=True, upload_to='post_images')),
                ('post_image3', models.ImageField(blank=True, upload_to='post_images')),
                ('post_image4', models.ImageField(blank=True, upload_to='post_images')),
                ('post_id', models.CharField(blank=True, max_length=255)),
                ('skill_keywords', models.CharField(choices=[('Skilled', 'Skilled'), ('Unskilled', 'Unskilled'), ('Semiskilled', 'Semiskilled')], default='Skilled', max_length=20)),
                ('tags', models.CharField(choices=[('Mason', 'Mason'), ('Carpenter', 'Carpenter'), ('Electician', 'Electrician'), ('Others', 'Others')], default='Mason', max_length=20)),
                ('post_created_on', models.DateTimeField(auto_now=True)),
                ('no_of_workers', models.IntegerField(blank=True)),
                ('is_active', models.BooleanField(default=1, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('isEmailVerified', models.BooleanField(default=0)),
                ('isMobilePhoneVerified', models.BooleanField(default=0)),
                ('phone_no', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], default='M', max_length=1)),
                ('dob', models.DateField(null=True)),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostReplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replier_name', models.CharField(max_length=100)),
                ('replier_id', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('is_selected', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.postmodel')),
            ],
        ),
    ]
