# Generated by Django 4.0.3 on 2022-03-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='post_created_on',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='work_id',
            field=models.IntegerField(null=True),
        ),
    ]
