# Generated by Django 4.0.3 on 2022-04-02 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_remove_postmodel_post_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreplies',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authorization.postmodel'),
        ),
    ]
